version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ofertaya_login_db
    environment:
      POSTGRES_DB: ofertaya
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ofertaya_net

  app:
    build: .
    container_name: ofertaya_login_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ofertaya
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - ofertaya_net

volumes:
  postgres_data:

networks:
  ofertaya_net:
